# Generated by Django 3.2.13 on 2022-09-18 14:21

import buy.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование Item')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Описание Item')),
                ('price', models.IntegerField(default=0, validators=[buy.validators.checking_positive_numbers], verbose_name='Стоимость Item')),
            ],
        ),
    ]
